version: '3.3'
services:
  dbEstoqueManager:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db_estoque_manager'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'usuar_padrao'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'dbpass12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root12345'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db-estoque-maneger:/var/lib/mysql
# Names our volume
volumes:
  db-estoque-maneger: